bases:
  - ./base
patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: klone-service
    path: service-patch.yaml
  - target:
      version: v1
      kind: Service
      name: debug-klone-service
    path: debug-service-patch.yaml
