apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"service2"},"name":"service2-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"service2"}},"template":{"metadata":{"labels":{"app":"service2"}},"spec":{"containers":[{"env":[{"name":"CONF_FILE","value":"/usr/src/app/configuration/service2-definition.yaml"}],"image":"shivamnagar/echo-relay:nightly","imagePullPolicy":"IfNotPresent","name":"service","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"10m","memory":"40Mi"}},"volumeMounts":[{"mountPath":"/usr/src/app/configuration/","name":"service2-volume"}]}],"volumes":[{"configMap":{"name":"service2-config"},"name":"service2-volume"}]}}}}
  creationTimestamp: "2022-12-07T07:53:59Z"
  generation: 3
  labels:
    app: service2
  name: service2-deployment
  namespace: default
  resourceVersion: "67101"
  uid: 63f7e1ce-42c0-419a-8719-8c0c7d2e5cba
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: service2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-12-07T15:46:08+05:30"
      creationTimestamp: null
      labels:
        app: service2
    spec:
      containers:
      - env:
        - name: CONF_FILE
          value: /usr/src/app/configuration/service2-definition.yaml
        image: shivamnagar/echo-relay:nightly
        imagePullPolicy: IfNotPresent
        name: service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 40Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/app/configuration/
          name: service2-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: service2-config
        name: service2-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-12-07T08:17:47Z"
    lastUpdateTime: "2022-12-07T10:16:41Z"
    message: ReplicaSet "service2-deployment-867985bbb8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-12-11T14:30:53Z"
    lastUpdateTime: "2022-12-11T14:30:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
